// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQpwuseY9KDnHor_radpAd_6wMxPt6M1c',
    appId: '1:676523788190:web:743dfcbc184eeafc0f788f',
    messagingSenderId: '676523788190',
    projectId: 'helpinghands-8a84b',
    authDomain: 'helpinghands-8a84b.firebaseapp.com',
    storageBucket: 'helpinghands-8a84b.appspot.com',
    measurementId: 'G-QTNHDDFEMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAds4G3IsakEzx-FGsiEzjxOsr9_XkL9tE',
    appId: '1:676523788190:android:6c374add300afa930f788f',
    messagingSenderId: '676523788190',
    projectId: 'helpinghands-8a84b',
    storageBucket: 'helpinghands-8a84b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuCl4xvCo2z-MrQybnnjlyHHOtGUrqTi4',
    appId: '1:676523788190:ios:02ba69a943b2be120f788f',
    messagingSenderId: '676523788190',
    projectId: 'helpinghands-8a84b',
    storageBucket: 'helpinghands-8a84b.appspot.com',
    iosClientId: '676523788190-mnj3mr49svgfocha23t2go0k92e123jb.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpingHand',
  );
}
